
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sggeszinrtkzpivgawzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnZ2VzemlucnRrenBpdmdhd3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDQ5MzMsImV4cCI6MjA1NjkyMDkzM30.Z4ykozhfU1D0JulqTlTWc0_ix910sUGStn6eN6mkPgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
